#cloud-config
bootcmd:
#- sed -i -e "s/mirrors.service.networklayer.com\|mirrors.service.softlayer.com/mirrors.adn.networklayer.com/g" /etc/yum.repos.d/*.repo*
- sed -i -e "s/mirrors.service.networklayer.com\|mirrors.service.softlayer.com/mirrors.adn.networklayer.com/g" /etc/cloud/cloud.cfg.d/*_networklayer_common.cfg
package_update: true
package_upgrade: true
packages:
  - nginx
write_files:
  - path: /init.bash
    content: |
      #!/bin/bash
      indexhtml=/var/www/html/index.nginx-debian.html

      # wait for the cloud-init boot process to complete
      until [ -f /$indexhtml ]; do
        date
        sleep 11
      done

      # initial value
      cat > $indexhtml <<EOF
      INIT
      EOF

      # Internet is availble then more software can be installed from the internet like
      # npm, pip, docker, ...  if isolated only the software from the ibm mirrors can be installed
      if curl -o /tmp/x https://www.python.org/downloads/release/python-373/; then
      cat > $indexhtml <<EOF
      INTERNET
      EOF
      else
      cat > $indexhtml <<EOF
      ISOLATED
      EOF
      fi

runcmd:
  - systemctl start nginx.service
  - bash -x /init.bash