# only run the test on master
branches:
  only:
  - master

# to easily encrypt values: https://travis-encrypt.github.io/

# https://docs.travis-ci.com/user/languages/minimal-and-generic/
language: minimal

# https://docs.travis-ci.com/user/notifications/#configuring-slack-notifications
notifications:
  slack:
    secure: l1RIDDiYcHqfCg0cHjHY7Tg+AaeZJ6mAtN9Z4dlrWwJpQy6mOePJ2dAjp6OJsPqaU+RNseGSsCiPdFnZT7y7R/w4dRymUieHK4exCfEa/1lVJPqf4+69OUcFdr4m1SeytApH0zv/jDf23EelusJlWxvRlC836HjWGCHSicVR+aYcJ5LMrHKKtnEr/f0eyJoNEtEsW7yJhOoEO9NznckMZXjVEtumOcPDZQ4mRpWZrXWADES8NOjNIWmECNwPQVQv4GlrMAQrw75pLBJ/8+Z6pMv0Fask9HFE5ThwscY7Ja4D7e3CXQdUJ/655PH154NqRnOZhLLA99+zheMpQJwtfCjdHWRDgGrnO6+chm5UlTzkHtEZGQ6/IowsJ38xTVBjBhkudE3Q6zvI0zQ7RfiLgA7LSyUy61YJczikSjJppXA4Ti/Y6NkbZJv/BC9SgGeQhDITAiPO6k4UTdNqk9O9SgokiPgT0dJAqg+1QfMKgWOMNREsLAmxUY8/lnymgnRReopk/j14AXtkoDvPAaiQDotKzu+2UFXo5iE0FE+VfDOR4hWVJwXGl3zNDuTWCXgXx0m9Iy31zkssR6t2aLxiIh3wyY0nMkFfR//2PqX8sFgS69vCKr6XL/o5U7GqNnnui4yiylI1Uyjliy/ebH+jhIiAKVAwZPQTBRXXg9f+SR0=

services:
  - docker

# https://docs.travis-ci.com/user/build-matrix/
env:
  global:
    - TEST_VPC_NAME=tests-us
    - RESOURCE_GROUP=automated-tests
    - REGION=us-south
  matrix:
    - SCENARIO=cleanup-initial TEST=tests/teardown.sh
    - SCENARIO=vpc-one-vsi TEST=tests/vpc-one-vsi/create-with-terraform.sh
    - SCENARIO=cleanup-vpc-one-vsi TEST=tests/teardown.sh
    - SCENARIO=vpc-public-app-private-backend TEST=tests/vpc-public-app-private-backend/create.sh
    - SCENARIO=cleanup-vpc-public-app-private-backend TEST=tests/teardown.sh
    - SCENARIO=vpc-public-app-private-backend TEST=tests/vpc-public-app-private-backend/create-with-terraform.sh TEARDOWN=tests/vpc-public-app-private-backend/teardown.sh
    - SCENARIO=cleanup-with-terraform-vpc-public-app-private-backend TEST=tests/teardown.sh
    - SCENARIO=vpc-site2site-vpn TEST=tests/vpc-site2site-vpn/create.sh
    - SCENARIO=cleanup-vpc-site2site-vpn TEST=tests/teardown.sh
    - SCENARIO=vpc-cockroachdb-mzr TEST=tests/vpc-cockroachdb-mzr/create.sh TEARDOWN=tests/vpc-cockroachdb-mzr/teardown.sh
    - SCENARIO=cleanup-vpc-cockroachdb-mzr TEST=tests/teardown.sh

script:
  - |
    docker run -i --volume $PWD:/root/mnt/home --workdir /root/mnt/home \
      --env SCENARIO \
      --env TEST \
      --env TEARDOWN \
      --env API_KEY \
      --env REGION \
      --env RESOURCE_GROUP \
      --env TEST_VPC_NAME \
      --env KEYS \
      --env JOB_ID=$TRAVIS_JOB_ID \
      l2fprod/bxshell tests/runner.sh
