- hosts: FRONT_NIC_IP BACK_NIC_IP
  remote_user: root
  tasks:
  - name: update yum cache
    yum:
      update_cache: yes
  - name: ensure apache is at the latest version
    yum:
      name: httpd
      state: latest
    notify:
    - restart apache
  - name: initialize php
    copy:
      dest: /var/www/html/info.php
      content: |
        <?php
        phpinfo();
        ?>
    notify:
    - restart apache
  - name: execute init.bash
    script: ./init.bash
  - name: execute bootstrapmin.sh
    script: ./bootstrapmin.sh

#  - name: write the apache config file
#    template:
#      src: /srv/httpd.j2
#      dest: /etc/httpd.conf
#    notify:
#    - restart apache
#  - name: ensure apache is running
#    service:
#      name: httpd
#      state: started
  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted
